// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Associated struct {
	ID            int64
	Cpf           string
	Name          string
	DateBirth     string
	MaritalStatus string
}
