// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Associated struct {
	NumberCard int64
	Name       string
}

type Present struct {
	AssociatedID int64
	MeetingID    int64
	Date         time.Time
	Present      bool
}
